#ifndef GUARD_CONSTANTS_SLATEPORT_SHOPS_H
#define GUARD_CONSTANTS_SLATEPORT_SHOPS_H

#define SLATEPORT_SHOP_ENERGY 0
#define SLATEPORT_SHOP_TM 1
#define SLATEPORT_SHOP_EVOLUTION 2
#define SLATEPORT_SHOP_FORMS 3
#define SLATEPORT_SHOP_MEGA 4
#define SLATEPORT_SHOP_Z 5
#define SLATEPORT_SHOP_TERA 6
#define SLATEPORT_SHOP_MINTS 7
#define SLATEPORT_SHOP_COUNT 8

#endif
