#ifndef GUARD_CONSTANTS_SPECIES_RANDOMIZER_H
#define GUARD_CONSTANTS_SPECIES_RANDOMIZER_H

#define SPECIES_REWARD_WILD    0x100
#define SPECIES_REWARD_STATIC  0x101
#define SPECIES_REWARD_GIFT    0x102
#define SPECIES_REWARD_EGG     0x103
#define SPECIES_REWARD_ROAMER  0x104
#define SPECIES_REWARD_TRADE   0x105
#define SPECIES_REWARD_STARTER 0x106

#define SPECIES_REWARD_FIRST_BATTLE 0x107
#define SPECIES_REWARD_OUTBREAK 0x108

#endif
