#include "global.h"
#include "remove_story.h"
#include "event_data.h"

static const u16 sAbsentActors[] =
{
    FLAG_HIDE_PETALBURG_WOODS_AQUA_GRUNT,
    FLAG_HIDE_RUSTBORO_CITY_AQUA_GRUNT,
    FLAG_HIDE_RUSTBORO_CITY_DEVON_EMPLOYEE_1,
    FLAG_HIDE_RUSTBORO_CITY_SCIENTIST,
    FLAG_HIDE_ROUTE_116_MR_BRINEY,
    FLAG_HIDE_RUSTURF_TUNNEL_BRINEY,
    FLAG_HIDE_RUSTURF_TUNNEL_PEEKO,
    FLAG_HIDE_RUSTURF_TUNNEL_AQUA_GRUNT,
    FLAG_HIDE_ROUTE_116_WANDAS_BOYFRIEND,
    FLAG_HIDE_SLATEPORT_CITY_TEAM_AQUA,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_AQUA_GRUNT,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_ARCHIE,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_SUBMARINE_SHADOW,
    FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_AQUA_GRUNTS,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_FAMILIAR_AQUA_GRUNT,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_ARCHIE,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_1,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_AQUA_GRUNT_2,
    FLAG_HIDE_SLATEPORT_CITY_OCEANIC_MUSEUM_2F_CAPTAIN_STERN,
    FLAG_HIDE_METEOR_FALLS_TEAM_AQUA,
    FLAG_HIDE_METEOR_FALLS_TEAM_MAGMA,
    FLAG_HIDE_METEOR_FALLS_1F_1R_COZMO,
    FLAG_HIDE_ROUTE_112_TEAM_MAGMA,
    FLAG_HIDE_MT_CHIMNEY_TEAM_AQUA,
    FLAG_HIDE_MT_CHIMNEY_TEAM_MAGMA,
    FLAG_HIDE_MT_PYRE_SUMMIT_ARCHIE,
    FLAG_HIDE_MT_PYRE_SUMMIT_TEAM_AQUA,
    FLAG_HIDE_MT_PYRE_SUMMIT_MAXIE,
    FLAG_HIDE_JAGGED_PASS_MAGMA_GUARD,
    FLAG_HIDE_ROUTE_119_TEAM_AQUA,
    FLAG_HIDE_ROUTE_110_TEAM_AQUA,
    FLAG_HIDE_ROUTE_121_TEAM_AQUA_GRUNTS,
    FLAG_HIDE_WEATHER_INSTITUTE_2F_AQUA_GRUNT_M,
    FLAG_HIDE_AQUA_HIDEOUT_GRUNTS,
    FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_1_BLOCKING_ENTRANCE,
    FLAG_HIDE_AQUA_HIDEOUT_1F_GRUNT_2_BLOCKING_ENTRANCE,
    FLAG_HIDE_AQUA_HIDEOUT_B2F_SUBMARINE_SHADOW,
    FLAG_HIDE_LILYCOVE_CITY_AQUA_GRUNTS,
    FLAG_HIDE_UNDERWATER_SEA_FLOOR_CAVERN_STOLEN_SUBMARINE,
    FLAG_HIDE_MAGMA_HIDEOUT_GRUNTS,
    FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON,
    FLAG_HIDE_MAGMA_HIDEOUT_4F_GROUDON_ASLEEP,
    FLAG_HIDE_SEAFLOOR_CAVERN_ENTRANCE_AQUA_GRUNT,
    FLAG_HIDE_SEAFLOOR_CAVERN_AQUA_GRUNTS,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_ARCHIE,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAXIE,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_MAGMA_GRUNTS,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE,
    FLAG_HIDE_SEAFLOOR_CAVERN_ROOM_9_KYOGRE_ASLEEP,
    FLAG_HIDE_ROUTE_128_ARCHIE,
    FLAG_HIDE_ROUTE_128_MAXIE,
    FLAG_HIDE_ROUTE_128_STEVEN,
    FLAG_HIDE_MOSSDEEP_CITY_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_1F_STEVEN,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_TEAM_MAGMA,
    FLAG_HIDE_MOSSDEEP_CITY_SPACE_CENTER_2F_STEVEN,
    FLAG_HIDE_SOOTOPOLIS_CITY_STEVEN,
    FLAG_HIDE_SOOTOPOLIS_CITY_RESIDENTS,
    FLAG_HIDE_CAVE_OF_ORIGIN_B1F_WALLACE,
    FLAG_HIDE_SOOTOPOLIS_CITY_ARCHIE,
    FLAG_HIDE_SOOTOPOLIS_CITY_MAXIE,
    FLAG_HIDE_SOOTOPOLIS_CITY_RAYQUAZA,
    FLAG_HIDE_SOOTOPOLIS_CITY_KYOGRE,
    FLAG_HIDE_SOOTOPOLIS_CITY_GROUDON,
};

static const u16 sPresentActors[] =
{
    FLAG_HIDE_PETALBURG_WOODS_DEVON_EMPLOYEE,
    FLAG_HIDE_RUSTURF_TUNNEL_WANDAS_BOYFRIEND,
    FLAG_HIDE_RUSTURF_TUNNEL_WANDA,
    FLAG_HIDE_SLATEPORT_CITY_HARBOR_CAPTAIN_STERN,
    FLAG_HIDE_SLATEPORT_MUSEUM_POPULATION,
    FLAG_HIDE_FALLARBOR_HOUSE_PROF_COZMO,
    FLAG_HIDE_MT_CHIMNEY_TRAINERS,
    FLAG_HIDE_MT_CHIMNEY_LAVA_COOKIE_LADY,
    FLAG_HIDE_WEATHER_INSTITUTE_1F_WORKERS,
    FLAG_HIDE_WEATHER_INSTITUTE_2F_WORKERS,
    FLAG_HIDE_SOOTOPOLIS_CITY_WALLACE,
    FLAG_HIDE_MOSSDEEP_CITY_STEVENS_HOUSE_STEVEN,
};

void InitRemoveStory(void)
{
    FlagSet(FLAG_HIDE_REMOVE_STORY_MUSEUM_ITEM);
    if (!FlagGet(FLAG_RUN_RULE_REMOVE_STORY))
        return;
    for (u32 i = 0; i < ARRAY_COUNT(sAbsentActors); i++)
        FlagSet(sAbsentActors[i]);
    for (u32 i = 0; i < ARRAY_COUNT(sPresentActors); i++)
        FlagClear(sPresentActors[i]);
    FlagClear(FLAG_HIDE_REMOVE_STORY_MUSEUM_ITEM);
    FlagSet(FLAG_RETURNED_DEVON_GOODS);
    FlagSet(FLAG_DELIVERED_DEVON_GOODS);
    FlagSet(FLAG_TEAM_AQUA_ESCAPED_IN_SUBMARINE);
    FlagSet(FLAG_KYOGRE_ESCAPED_SEAFLOOR_CAVERN);
    FlagSet(FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY);
    VarSet(VAR_PETALBURG_WOODS_STATE, 1);
    VarSet(VAR_ROUTE116_STATE, 2);
    VarSet(VAR_RUSTURF_TUNNEL_STATE, 3);
    VarSet(VAR_DEVON_CORP_3F_STATE, 1);
    VarSet(VAR_METEOR_FALLS_STATE, 1);
    VarSet(VAR_MT_PYRE_STATE, 1);
    VarSet(VAR_ROUTE121_STATE, 1);
    VarSet(VAR_WEATHER_INSTITUTE_STATE, 1);
    VarSet(VAR_JAGGED_PASS_STATE, 2);
    VarSet(VAR_SEAFLOOR_CAVERN_STATE, 1);
    VarSet(VAR_STEVENS_HOUSE_STATE, 2);
}

void RemoveStoryAfterRoxanne(void)
{
    if (!FlagGet(FLAG_RUN_RULE_REMOVE_STORY) || !FlagGet(FLAG_BADGE01_GET))
        return;
    VarSet(VAR_RUSTBORO_CITY_STATE, 7);
    VarSet(VAR_ROUTE104_STATE, 1);
    VarSet(VAR_BRINEY_LOCATION, 1);
    FlagClear(FLAG_HIDE_ROUTE_116_DEVON_EMPLOYEE);
    FlagClear(FLAG_HIDE_BRINEYS_HOUSE_MR_BRINEY);
    FlagClear(FLAG_HIDE_BRINEYS_HOUSE_PEEKO);
    FlagClear(FLAG_HIDE_RUSTBORO_CITY_RIVAL);
}
